name: Setup Rust Environment
description: Install deps, ARM toolchain, and Rust toolchain
inputs:
  embedded:
    description: "Set to true to install the embedded development tools"
    required: false
    default: "true"
  cargo-dependencies:
    description: List of cargo dependencies to install (space separated)
runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y cmake protobuf-compiler
    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi
    - name: Install Rust toolchain
      shell: bash
      run: rustup install stable
    - name: Install Embedded Development Dependencies
      shell: bash
      if: ${{ inputs.embedded == 'true' }}
      run: rustup target add thumbv7em-none-eabihf
    - name: Install Cargo Dependencies
      shell: bash
      if: ${{ inputs.cargo-dependencies != '' }}
      run: cargo install --force ${{ inputs.cargo-dependencies }}
