[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

# -----------------------
# Host Testing
# -----------------------

[tasks.test-host]
dependencies = [
    "test-thermocouple",
]

# -----------------------
# Embedded Testing
# -----------------------

[tasks.test-device]
dependencies = [
    "test-temperature-board",
    "test-pressure-board",
    "test-strain-board",
    "test-common-arm",
]

[tasks.test-common-arm]
command = "cargo"
args = ["test", "-p", "common-arm", "${@}"]

[tasks.test-temperature-board]
command = "cargo"
args = ["test", "-p", "temperature", "${@}"]

[tasks.test-pressure-board]
command = "cargo"
args = ["test", "-p", "pressure", "${@}"]

[tasks.test-strain-board]
command = "cargo"
args = ["test", "-p", "strain", "${@}"]

[tasks.test-thermocouple]
command = "cargo"
args = ["test", "-p", "thermocouple-converter", "--target", "${CARGO_MAKE_RUST_TARGET_TRIPLE}"]
env = {RUST_MIN_STACK = "8388608"}