[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# This runner needs to be parametric so we can pass in the chip name
runner = "probe-rs run --chip ${PROBE_RS_CHIP} --protocol swd"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[env]
DEFMT_LOG = "debug"
PROBE_RS_CHIP = "STM32H733VGTx"

#[build]
# Do not set a global target at the workspace level so that
# non-embedded crates build for the host by default. Board crates
# under `boards/**` set their own target in a local .cargo/config.toml.
