[package]
name = "argus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
common-arm = { path = "../../crates/common-arm" }
defmt = { workspace = true }
embedded-alloc = {workspace = true}
heapless = {workspace = true}
defmt-rtt = { workspace = true }
panic-probe = { workspace = true }
chrono = { workspace = true }
enum_dispatch = {workspace = true}
ads126x = {path = "../../crates/ads126x"}
smlang = {workspace = true}
libm = "0.2.15"
messages-prost = { workspace = true }
# Change stm32h743bi to your chip name, if necessary.
embassy-stm32 = { version = "0.2.0", features = ["defmt", "stm32h743bi", "time-driver-tim2", "exti", "memory-x", "unstable-pac", "chrono"] }
embassy-sync = { version = "0.6.2", features = ["defmt"] }
embassy-embedded-hal = { version = "0.3.0" }
embassy-executor = { version = "0.7.0", features = ["nightly", "task-arena-size-10240", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-net = { version = "0.7.0", features = ["defmt", "tcp", "dhcpv4", "medium-ethernet", "proto-ipv6", "dns"] }
embassy-usb = { version = "0.4.0", features = ["defmt"] }
embassy-futures = { version = "0.1.0" }
embedded-hal-bus = "0.3.0"
embedded-sdmmc = "0.9.0"
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = { version = "1.0" }
embedded-nal-async = "0.8.0"
embedded-io-async = { version = "0.6.1" }
critical-section = "1.1"
micromath = "2.0.0"
stm32-fmc = "0.3.0"
embedded-storage = "0.3.1"
static_cell = "2"
grounded = "0.2.0"
pid = "4.0.0"
thermocouple-converter = { path = "../../crates/thermocouple-converter" }
straingauge-converter = { path = "../../crates/straingauge-converter" }

[dev-dependencies]
defmt-test = { workspace = true }

[[test]]
name = "sd"
harness = false
path = "tests/sd.rs"

[[test]]
name = "adc"
harness = false
path = "tests/adc.rs"

[[bin]]
name = "argus"
harness = false

[features]
pressure = []
temperature = []
strain = []


