[package]
name = "argus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
rtic = { workspace = true }
rtic-monotonics = { workspace = true }
common-arm = { path = "../../crates/common-arm" }
stm32h7xx-hal = { workspace = true }
postcard = { workspace = true }
defmt = { workspace = true }
fdcan = { workspace = true }
embedded-alloc = {workspace = true}
heapless = {workspace = true}
rtic-sync = { workspace = true }
defmt-rtt = { workspace = true }
panic-probe = { workspace = true }
chrono = { workspace = true }
enum_dispatch = {workspace = true}
messages = {workspace = true}
ads126x = { workspace = true }
smlang = {workspace = true}
embedded-hal = {workspace = true}
thermocouple-converter = { path = "../../crates/thermocouple-converter" }

[dev-dependencies]
defmt-test = { workspace = true }

[[test]]
name = "sd"
harness = false
path = "tests/sd.rs"

[[test]]
name = "adc"
harness = false
path = "tests/adc.rs"

[[test]]
name = "simple"
harness = false
path = "tests/simple.rs"

[[bin]]
name = "argus"
harness = false

[features]
pressure = []
temperature = []
strain = []