# SHOULD DO: dedupe these and clean them up
on:
  push:
    branches: [ master ]
  pull_request:

name: Build Verification

jobs:
  formatting:
    name: Check for Formatting Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-environment/
        with:
          embedded: true
          cargo-dependencies: "cargo-make cargo-fmt"
      - name: Check Formatting
        run: cargo fmt -- --check

  build_pressure:
    name: Build with Pressure Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-environment/
        with:
          embedded: true
          cargo-dependencies: "cargo-make"

      - name: "Build with Pressure Feature"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features pressure

  build_temperature:
    name: Build with Temperature Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-environment/
        with:
          embedded: true
          cargo-dependencies: "cargo-make"

      - name: "Build with Temperature Feature"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features temperature

  build_strain:
    name: Build with Strain Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-environment/
        with:
          embedded: true
          cargo-dependencies: "cargo-make"

      - name: "Build with Strain Feature"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features strain

  test:
    runs-on: ubuntu-latest
    env:
      RUST_MIN_STACK: 8388608
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-environment/

      - uses: actions-rs/cargo@v1
        name: "Run Host Tests"
        with:
          command: make
          args: test-host