# SHOULD DO: dedupe these and clean them up
on:
  push:
    branches: [ master ]
  pull_request:

name: Build Verification

jobs:
  build_environment:
    name: Build Environment Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-environment/
        with:
          embedded: true
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  formatting:
    name: Check for Formatting Issues
    needs: build_environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Rust Environment Cache
        uses: ./.github/actions/restore-environment-cache/
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check Formatting
        run: cargo fmt -- --check

  build_pressure:
    name: Build with Pressure Feature
    needs: build_environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Rust Environment Cache
        uses: ./.github/actions/restore-environment-cache/
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: "Build with Pressure Feature"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features pressure

  build_temperature:
    name: Build with Temperature Feature
    needs: build_environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Rust Environment Cache
        uses: ./.github/actions/restore-environment-cache/
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: "Build with Temperature Feature"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features temperature

  build_strain:
    name: Build with Strain Feature
    needs: build_environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Rust Environment Cache
        uses: ./.github/actions/restore-environment-cache/
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: "Build with Strain Feature"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features strain

  test:
    name: Run Host Tests
    needs: build_environment
    runs-on: ubuntu-latest
    env:
      RUST_MIN_STACK: 8388608
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Rust Environment Cache
        uses: ./.github/actions/restore-environment-cache/
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        name: "Run Host Tests"
        with:
          command: make
          args: test-host